# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './appMainWindow/ui.ui'
#
# Created: Mon Apr 20 03:36:32 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(900, 900)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 900))
        MainWindow.setMaximumSize(QtCore.QSize(900, 900))
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setIconSize(QtCore.QSize(44, 44))
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(_fromUtf8("background-color: #B8B8B8"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 100))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.layoutWidget = QtGui.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 30, 905, 758))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.Wgt_Mpl_ToolBar = QtGui.QWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wgt_Mpl_ToolBar.sizePolicy().hasHeightForWidth())
        self.Wgt_Mpl_ToolBar.setSizePolicy(sizePolicy)
        self.Wgt_Mpl_ToolBar.setMinimumSize(QtCore.QSize(0, 50))
        self.Wgt_Mpl_ToolBar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.Wgt_Mpl_ToolBar.setObjectName(_fromUtf8("Wgt_Mpl_ToolBar"))
        self.horizontalLayout.addWidget(self.Wgt_Mpl_ToolBar)
        self.Btn_Reset = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Reset.sizePolicy().hasHeightForWidth())
        self.Btn_Reset.setSizePolicy(sizePolicy)
        self.Btn_Reset.setMinimumSize(QtCore.QSize(50, 50))
        self.Btn_Reset.setMaximumSize(QtCore.QSize(50, 50))
        self.Btn_Reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_Reset.setAutoFillBackground(False)
        self.Btn_Reset.setStyleSheet(_fromUtf8(""))
        self.Btn_Reset.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/reset.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Btn_Reset.setIcon(icon1)
        self.Btn_Reset.setIconSize(QtCore.QSize(50, 50))
        self.Btn_Reset.setFlat(False)
        self.Btn_Reset.setObjectName(_fromUtf8("Btn_Reset"))
        self.horizontalLayout.addWidget(self.Btn_Reset)
        self.pushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(50, 50))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet(_fromUtf8(""))
        self.pushButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.MainTab = QtGui.QTabWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainTab.sizePolicy().hasHeightForWidth())
        self.MainTab.setSizePolicy(sizePolicy)
        self.MainTab.setMinimumSize(QtCore.QSize(900, 700))
        self.MainTab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.MainTab.setTabsClosable(False)
        self.MainTab.setMovable(True)
        self.MainTab.setObjectName(_fromUtf8("MainTab"))
        self.Tab_Import = QtGui.QWidget()
        self.Tab_Import.setObjectName(_fromUtf8("Tab_Import"))
        self.gridLayout_7 = QtGui.QGridLayout(self.Tab_Import)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.widget_3 = QtGui.QWidget(self.Tab_Import)
        self.widget_3.setMinimumSize(QtCore.QSize(300, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.widget_3)
        self.verticalLayout_15.setMargin(0)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.LEdt_LastRowNumber = QtGui.QLineEdit(self.widget_3)
        self.LEdt_LastRowNumber.setEnabled(False)
        self.LEdt_LastRowNumber.setMaximumSize(QtCore.QSize(100, 16777215))
        self.LEdt_LastRowNumber.setObjectName(_fromUtf8("LEdt_LastRowNumber"))
        self.gridLayout_11.addWidget(self.LEdt_LastRowNumber, 2, 2, 1, 1)
        self.LEdt_ThirstColumnNumber = QtGui.QLineEdit(self.widget_3)
        self.LEdt_ThirstColumnNumber.setEnabled(False)
        self.LEdt_ThirstColumnNumber.setMaximumSize(QtCore.QSize(100, 16777215))
        self.LEdt_ThirstColumnNumber.setObjectName(_fromUtf8("LEdt_ThirstColumnNumber"))
        self.gridLayout_11.addWidget(self.LEdt_ThirstColumnNumber, 3, 2, 1, 1)
        self.RBtn_ThirstRowNumber = QtGui.QRadioButton(self.widget_3)
        self.RBtn_ThirstRowNumber.setMaximumSize(QtCore.QSize(20, 16777215))
        self.RBtn_ThirstRowNumber.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RBtn_ThirstRowNumber.setText(_fromUtf8(""))
        self.RBtn_ThirstRowNumber.setAutoExclusive(False)
        self.RBtn_ThirstRowNumber.setObjectName(_fromUtf8("RBtn_ThirstRowNumber"))
        self.gridLayout_11.addWidget(self.RBtn_ThirstRowNumber, 1, 0, 1, 1)
        self.RBtn_LastColumnNumber = QtGui.QRadioButton(self.widget_3)
        self.RBtn_LastColumnNumber.setMaximumSize(QtCore.QSize(20, 16777215))
        self.RBtn_LastColumnNumber.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RBtn_LastColumnNumber.setText(_fromUtf8(""))
        self.RBtn_LastColumnNumber.setAutoExclusive(False)
        self.RBtn_LastColumnNumber.setObjectName(_fromUtf8("RBtn_LastColumnNumber"))
        self.gridLayout_11.addWidget(self.RBtn_LastColumnNumber, 4, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.widget_3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_11.addWidget(self.label_20, 5, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.widget_3)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_11.addWidget(self.label_19, 2, 1, 1, 1)
        self.RBtn_SplitterMask = QtGui.QRadioButton(self.widget_3)
        self.RBtn_SplitterMask.setMaximumSize(QtCore.QSize(20, 16777215))
        self.RBtn_SplitterMask.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RBtn_SplitterMask.setText(_fromUtf8(""))
        self.RBtn_SplitterMask.setAutoExclusive(False)
        self.RBtn_SplitterMask.setObjectName(_fromUtf8("RBtn_SplitterMask"))
        self.gridLayout_11.addWidget(self.RBtn_SplitterMask, 5, 0, 1, 1)
        self.LEdt_LastColumnNumber = QtGui.QLineEdit(self.widget_3)
        self.LEdt_LastColumnNumber.setEnabled(False)
        self.LEdt_LastColumnNumber.setMaximumSize(QtCore.QSize(100, 16777215))
        self.LEdt_LastColumnNumber.setObjectName(_fromUtf8("LEdt_LastColumnNumber"))
        self.gridLayout_11.addWidget(self.LEdt_LastColumnNumber, 4, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.widget_3)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_11.addWidget(self.label_13, 3, 1, 1, 1)
        self.RBtn_ThirstColumnNumber = QtGui.QRadioButton(self.widget_3)
        self.RBtn_ThirstColumnNumber.setMaximumSize(QtCore.QSize(20, 16777215))
        self.RBtn_ThirstColumnNumber.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RBtn_ThirstColumnNumber.setText(_fromUtf8(""))
        self.RBtn_ThirstColumnNumber.setAutoExclusive(False)
        self.RBtn_ThirstColumnNumber.setObjectName(_fromUtf8("RBtn_ThirstColumnNumber"))
        self.gridLayout_11.addWidget(self.RBtn_ThirstColumnNumber, 3, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.widget_3)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_11.addWidget(self.label_17, 1, 1, 1, 1)
        self.LEdt_ThirstRowNumber = QtGui.QLineEdit(self.widget_3)
        self.LEdt_ThirstRowNumber.setEnabled(False)
        self.LEdt_ThirstRowNumber.setMaximumSize(QtCore.QSize(100, 16777215))
        self.LEdt_ThirstRowNumber.setObjectName(_fromUtf8("LEdt_ThirstRowNumber"))
        self.gridLayout_11.addWidget(self.LEdt_ThirstRowNumber, 1, 2, 1, 1)
        self.LEdt_SplitterMask = QtGui.QLineEdit(self.widget_3)
        self.LEdt_SplitterMask.setEnabled(False)
        self.LEdt_SplitterMask.setMaximumSize(QtCore.QSize(100, 16777215))
        self.LEdt_SplitterMask.setObjectName(_fromUtf8("LEdt_SplitterMask"))
        self.gridLayout_11.addWidget(self.LEdt_SplitterMask, 5, 2, 1, 1)
        self.Btn_Import_ChooseFile = QtGui.QPushButton(self.widget_3)
        self.Btn_Import_ChooseFile.setObjectName(_fromUtf8("Btn_Import_ChooseFile"))
        self.gridLayout_11.addWidget(self.Btn_Import_ChooseFile, 0, 1, 1, 1)
        self.LEdt_ImportFileName = QtGui.QLineEdit(self.widget_3)
        self.LEdt_ImportFileName.setEnabled(True)
        self.LEdt_ImportFileName.setMaximumSize(QtCore.QSize(100, 16777215))
        self.LEdt_ImportFileName.setText(_fromUtf8(""))
        self.LEdt_ImportFileName.setObjectName(_fromUtf8("LEdt_ImportFileName"))
        self.gridLayout_11.addWidget(self.LEdt_ImportFileName, 0, 2, 1, 1)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.RBtn_PropInR = QtGui.QRadioButton(self.widget_3)
        self.RBtn_PropInR.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RBtn_PropInR.setChecked(True)
        self.RBtn_PropInR.setObjectName(_fromUtf8("RBtn_PropInR"))
        self.verticalLayout_16.addWidget(self.RBtn_PropInR)
        self.RBtn_PropInC = QtGui.QRadioButton(self.widget_3)
        self.RBtn_PropInC.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RBtn_PropInC.setObjectName(_fromUtf8("RBtn_PropInC"))
        self.verticalLayout_16.addWidget(self.RBtn_PropInC)
        self.gridLayout_11.addLayout(self.verticalLayout_16, 6, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.widget_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_11.addWidget(self.label_15, 6, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.widget_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_11.addWidget(self.label_18, 7, 1, 1, 1)
        self.RBtn_LastRowNumber = QtGui.QRadioButton(self.widget_3)
        self.RBtn_LastRowNumber.setMaximumSize(QtCore.QSize(20, 16777215))
        self.RBtn_LastRowNumber.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RBtn_LastRowNumber.setText(_fromUtf8(""))
        self.RBtn_LastRowNumber.setAutoExclusive(False)
        self.RBtn_LastRowNumber.setObjectName(_fromUtf8("RBtn_LastRowNumber"))
        self.gridLayout_11.addWidget(self.RBtn_LastRowNumber, 2, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.widget_3)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_11.addWidget(self.label_16, 4, 1, 1, 1)
        self.RBtn_NamesInFile_Obj = QtGui.QRadioButton(self.widget_3)
        self.RBtn_NamesInFile_Obj.setMaximumSize(QtCore.QSize(20, 16777215))
        self.RBtn_NamesInFile_Obj.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RBtn_NamesInFile_Obj.setText(_fromUtf8(""))
        self.RBtn_NamesInFile_Obj.setChecked(True)
        self.RBtn_NamesInFile_Obj.setAutoExclusive(False)
        self.RBtn_NamesInFile_Obj.setObjectName(_fromUtf8("RBtn_NamesInFile_Obj"))
        self.gridLayout_11.addWidget(self.RBtn_NamesInFile_Obj, 7, 0, 1, 1)
        self.RBtn_NamesInFile_Param = QtGui.QRadioButton(self.widget_3)
        self.RBtn_NamesInFile_Param.setMaximumSize(QtCore.QSize(20, 16777215))
        self.RBtn_NamesInFile_Param.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RBtn_NamesInFile_Param.setText(_fromUtf8(""))
        self.RBtn_NamesInFile_Param.setChecked(True)
        self.RBtn_NamesInFile_Param.setAutoExclusive(False)
        self.RBtn_NamesInFile_Param.setObjectName(_fromUtf8("RBtn_NamesInFile_Param"))
        self.gridLayout_11.addWidget(self.RBtn_NamesInFile_Param, 8, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.widget_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_11.addWidget(self.label_21, 8, 1, 1, 1)
        self.label = QtGui.QLabel(self.widget_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_11.addWidget(self.label, 9, 1, 1, 1)
        self.RBtn_ClassesInFile = QtGui.QRadioButton(self.widget_3)
        self.RBtn_ClassesInFile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RBtn_ClassesInFile.setText(_fromUtf8(""))
        self.RBtn_ClassesInFile.setChecked(True)
        self.RBtn_ClassesInFile.setAutoExclusive(False)
        self.RBtn_ClassesInFile.setObjectName(_fromUtf8("RBtn_ClassesInFile"))
        self.gridLayout_11.addWidget(self.RBtn_ClassesInFile, 9, 0, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout_11)
        self.Btn_Import = QtGui.QPushButton(self.widget_3)
        self.Btn_Import.setMinimumSize(QtCore.QSize(100, 0))
        self.Btn_Import.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_Import.setObjectName(_fromUtf8("Btn_Import"))
        self.verticalLayout_14.addWidget(self.Btn_Import)
        self.Btn_PrepareDate = QtGui.QPushButton(self.widget_3)
        self.Btn_PrepareDate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Btn_PrepareDate.setObjectName(_fromUtf8("Btn_PrepareDate"))
        self.verticalLayout_14.addWidget(self.Btn_PrepareDate)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_23 = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_13.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_13.addWidget(self.label_22, 0, 0, 1, 1)
        self.Lbl_NumObj = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Lbl_NumObj.setFont(font)
        self.Lbl_NumObj.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.Lbl_NumObj.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Lbl_NumObj.setObjectName(_fromUtf8("Lbl_NumObj"))
        self.gridLayout_13.addWidget(self.Lbl_NumObj, 0, 1, 1, 1)
        self.Lbl_NumPrp = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Lbl_NumPrp.setFont(font)
        self.Lbl_NumPrp.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.Lbl_NumPrp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Lbl_NumPrp.setObjectName(_fromUtf8("Lbl_NumPrp"))
        self.gridLayout_13.addWidget(self.Lbl_NumPrp, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_13.addWidget(self.label_2, 2, 0, 1, 1)
        self.Lbl_NumCls = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Lbl_NumCls.setFont(font)
        self.Lbl_NumCls.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.Lbl_NumCls.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Lbl_NumCls.setObjectName(_fromUtf8("Lbl_NumCls"))
        self.gridLayout_13.addWidget(self.Lbl_NumCls, 2, 1, 1, 1)
        self.verticalLayout_14.addLayout(self.gridLayout_13)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem1)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.horizontalLayout_5.addWidget(self.widget_3)
        self.widget_4 = QtGui.QWidget(self.Tab_Import)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.widget_4)
        self.verticalLayout_13.setMargin(0)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.Wgt_Import_M = QtGui.QWidget(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wgt_Import_M.sizePolicy().hasHeightForWidth())
        self.Wgt_Import_M.setSizePolicy(sizePolicy)
        self.Wgt_Import_M.setMinimumSize(QtCore.QSize(0, 0))
        self.Wgt_Import_M.setObjectName(_fromUtf8("Wgt_Import_M"))
        self.verticalLayout_12.addWidget(self.Wgt_Import_M)
        self.Wgt_Import_MV = QtGui.QWidget(self.widget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wgt_Import_MV.sizePolicy().hasHeightForWidth())
        self.Wgt_Import_MV.setSizePolicy(sizePolicy)
        self.Wgt_Import_MV.setObjectName(_fromUtf8("Wgt_Import_MV"))
        self.verticalLayout_12.addWidget(self.Wgt_Import_MV)
        spacerItem2 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_12.addItem(spacerItem2)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.horizontalLayout_5.addWidget(self.widget_4)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/load.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MainTab.addTab(self.Tab_Import, icon3, _fromUtf8(""))
        self.Tab_Transform = QtGui.QWidget()
        self.Tab_Transform.setObjectName(_fromUtf8("Tab_Transform"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.Tab_Transform)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_12 = QtGui.QLabel(self.Tab_Transform)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_3.addWidget(self.label_12)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.RBtn_UsePC = QtGui.QRadioButton(self.Tab_Transform)
        self.RBtn_UsePC.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RBtn_UsePC.setChecked(True)
        self.RBtn_UsePC.setAutoExclusive(False)
        self.RBtn_UsePC.setObjectName(_fromUtf8("RBtn_UsePC"))
        self.verticalLayout_7.addWidget(self.RBtn_UsePC)
        self.radioButton_2 = QtGui.QRadioButton(self.Tab_Transform)
        self.radioButton_2.setEnabled(False)
        self.radioButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.verticalLayout_7.addWidget(self.radioButton_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.RBtn_PC_scale = QtGui.QRadioButton(self.Tab_Transform)
        self.RBtn_PC_scale.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RBtn_PC_scale.setChecked(True)
        self.RBtn_PC_scale.setAutoExclusive(False)
        self.RBtn_PC_scale.setObjectName(_fromUtf8("RBtn_PC_scale"))
        self.verticalLayout_6.addWidget(self.RBtn_PC_scale)
        self.Btn_CalculatePC = QtGui.QPushButton(self.Tab_Transform)
        self.Btn_CalculatePC.setObjectName(_fromUtf8("Btn_CalculatePC"))
        self.verticalLayout_6.addWidget(self.Btn_CalculatePC)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_14 = QtGui.QLabel(self.Tab_Transform)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 1, 1, 1, 1)
        self.LEdt_PC_thr = QtGui.QLineEdit(self.Tab_Transform)
        self.LEdt_PC_thr.setEnabled(False)
        self.LEdt_PC_thr.setText(_fromUtf8(""))
        self.LEdt_PC_thr.setObjectName(_fromUtf8("LEdt_PC_thr"))
        self.gridLayout_3.addWidget(self.LEdt_PC_thr, 0, 2, 1, 1)
        self.LEdt_PC_dim = QtGui.QLineEdit(self.Tab_Transform)
        self.LEdt_PC_dim.setObjectName(_fromUtf8("LEdt_PC_dim"))
        self.gridLayout_3.addWidget(self.LEdt_PC_dim, 1, 2, 1, 1)
        self.RBtn_PC_dim = QtGui.QRadioButton(self.Tab_Transform)
        self.RBtn_PC_dim.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RBtn_PC_dim.setText(_fromUtf8(""))
        self.RBtn_PC_dim.setChecked(True)
        self.RBtn_PC_dim.setObjectName(_fromUtf8("RBtn_PC_dim"))
        self.gridLayout_3.addWidget(self.RBtn_PC_dim, 1, 0, 1, 1)
        self.RBtn_PC_thr = QtGui.QRadioButton(self.Tab_Transform)
        self.RBtn_PC_thr.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RBtn_PC_thr.setText(_fromUtf8(""))
        self.RBtn_PC_thr.setChecked(False)
        self.RBtn_PC_thr.setAutoExclusive(True)
        self.RBtn_PC_thr.setObjectName(_fromUtf8("RBtn_PC_thr"))
        self.gridLayout_3.addWidget(self.RBtn_PC_thr, 0, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.Tab_Transform)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 0, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        self.Btn_ReducePC = QtGui.QPushButton(self.Tab_Transform)
        self.Btn_ReducePC.setObjectName(_fromUtf8("Btn_ReducePC"))
        self.verticalLayout_6.addWidget(self.Btn_ReducePC)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.Lbl_PCdim = QtGui.QLabel(self.Tab_Transform)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Lbl_PCdim.setFont(font)
        self.Lbl_PCdim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Lbl_PCdim.setObjectName(_fromUtf8("Lbl_PCdim"))
        self.gridLayout_2.addWidget(self.Lbl_PCdim, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.Tab_Transform)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.Tab_Transform)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.Lbl_PCvar = QtGui.QLabel(self.Tab_Transform)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Lbl_PCvar.setFont(font)
        self.Lbl_PCvar.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Lbl_PCvar.setObjectName(_fromUtf8("Lbl_PCvar"))
        self.gridLayout_2.addWidget(self.Lbl_PCvar, 1, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.Wgt_Transform = QtGui.QWidget(self.Tab_Transform)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wgt_Transform.sizePolicy().hasHeightForWidth())
        self.Wgt_Transform.setSizePolicy(sizePolicy)
        self.Wgt_Transform.setMinimumSize(QtCore.QSize(600, 0))
        self.Wgt_Transform.setMaximumSize(QtCore.QSize(600, 500))
        self.Wgt_Transform.setObjectName(_fromUtf8("Wgt_Transform"))
        self.verticalLayout_9.addWidget(self.Wgt_Transform)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/transform.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MainTab.addTab(self.Tab_Transform, icon4, _fromUtf8(""))
        self.Tab_plot = QtGui.QWidget()
        self.Tab_plot.setObjectName(_fromUtf8("Tab_plot"))
        self.gridLayout_4 = QtGui.QGridLayout(self.Tab_plot)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.Wgt_MultiGraphPlot2 = QtGui.QWidget(self.Tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wgt_MultiGraphPlot2.sizePolicy().hasHeightForWidth())
        self.Wgt_MultiGraphPlot2.setSizePolicy(sizePolicy)
        self.Wgt_MultiGraphPlot2.setMinimumSize(QtCore.QSize(0, 310))
        self.Wgt_MultiGraphPlot2.setMaximumSize(QtCore.QSize(16777215, 310))
        self.Wgt_MultiGraphPlot2.setObjectName(_fromUtf8("Wgt_MultiGraphPlot2"))
        self.gridLayout.addWidget(self.Wgt_MultiGraphPlot2, 1, 1, 1, 1)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.RBtn_MultiGraphPlot_UsePC1 = QtGui.QRadioButton(self.Tab_plot)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBtn_MultiGraphPlot_UsePC1.setFont(font)
        self.RBtn_MultiGraphPlot_UsePC1.setChecked(False)
        self.RBtn_MultiGraphPlot_UsePC1.setAutoExclusive(False)
        self.RBtn_MultiGraphPlot_UsePC1.setObjectName(_fromUtf8("RBtn_MultiGraphPlot_UsePC1"))
        self.verticalLayout_10.addWidget(self.RBtn_MultiGraphPlot_UsePC1)
        self.RBtn_MultiGraphPlot_UsePCred1 = QtGui.QRadioButton(self.Tab_plot)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBtn_MultiGraphPlot_UsePCred1.setFont(font)
        self.RBtn_MultiGraphPlot_UsePCred1.setChecked(False)
        self.RBtn_MultiGraphPlot_UsePCred1.setAutoExclusive(False)
        self.RBtn_MultiGraphPlot_UsePCred1.setObjectName(_fromUtf8("RBtn_MultiGraphPlot_UsePCred1"))
        self.verticalLayout_10.addWidget(self.RBtn_MultiGraphPlot_UsePCred1)
        self.Btn_MultiGraphPlot1 = QtGui.QPushButton(self.Tab_plot)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Btn_MultiGraphPlot1.setFont(font)
        self.Btn_MultiGraphPlot1.setObjectName(_fromUtf8("Btn_MultiGraphPlot1"))
        self.verticalLayout_10.addWidget(self.Btn_MultiGraphPlot1)
        self.gridLayout.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.Wgt_MultiGraphPlot1 = QtGui.QWidget(self.Tab_plot)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Wgt_MultiGraphPlot1.sizePolicy().hasHeightForWidth())
        self.Wgt_MultiGraphPlot1.setSizePolicy(sizePolicy)
        self.Wgt_MultiGraphPlot1.setMinimumSize(QtCore.QSize(0, 310))
        self.Wgt_MultiGraphPlot1.setMaximumSize(QtCore.QSize(16777215, 310))
        self.Wgt_MultiGraphPlot1.setObjectName(_fromUtf8("Wgt_MultiGraphPlot1"))
        self.gridLayout.addWidget(self.Wgt_MultiGraphPlot1, 0, 1, 1, 1)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.RBtn_MultiGraphPlot_UsePC2 = QtGui.QRadioButton(self.Tab_plot)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBtn_MultiGraphPlot_UsePC2.setFont(font)
        self.RBtn_MultiGraphPlot_UsePC2.setChecked(False)
        self.RBtn_MultiGraphPlot_UsePC2.setAutoExclusive(False)
        self.RBtn_MultiGraphPlot_UsePC2.setObjectName(_fromUtf8("RBtn_MultiGraphPlot_UsePC2"))
        self.verticalLayout_11.addWidget(self.RBtn_MultiGraphPlot_UsePC2)
        self.RBtn_MultiGraphPlot_UsePCred2 = QtGui.QRadioButton(self.Tab_plot)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RBtn_MultiGraphPlot_UsePCred2.setFont(font)
        self.RBtn_MultiGraphPlot_UsePCred2.setChecked(False)
        self.RBtn_MultiGraphPlot_UsePCred2.setAutoExclusive(False)
        self.RBtn_MultiGraphPlot_UsePCred2.setObjectName(_fromUtf8("RBtn_MultiGraphPlot_UsePCred2"))
        self.verticalLayout_11.addWidget(self.RBtn_MultiGraphPlot_UsePCred2)
        self.Btn_MultiGraphPlot2 = QtGui.QPushButton(self.Tab_plot)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Btn_MultiGraphPlot2.setFont(font)
        self.Btn_MultiGraphPlot2.setObjectName(_fromUtf8("Btn_MultiGraphPlot2"))
        self.verticalLayout_11.addWidget(self.Btn_MultiGraphPlot2)
        self.gridLayout.addLayout(self.verticalLayout_11, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/plot.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MainTab.addTab(self.Tab_plot, icon5, _fromUtf8(""))
        self.Tab_Console = QtGui.QWidget()
        self.Tab_Console.setObjectName(_fromUtf8("Tab_Console"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.Tab_Console)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.Tedt_Console = QtGui.QTextEdit(self.Tab_Console)
        self.Tedt_Console.setEnabled(True)
        self.Tedt_Console.setReadOnly(True)
        self.Tedt_Console.setObjectName(_fromUtf8("Tedt_Console"))
        self.horizontalLayout_2.addWidget(self.Tedt_Console)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/console.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MainTab.addTab(self.Tab_Console, icon6, _fromUtf8(""))
        self.Tab_Info = QtGui.QWidget()
        self.Tab_Info.setObjectName(_fromUtf8("Tab_Info"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Tab_Info)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(14, -1, 14, -1)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.textEdit = QtGui.QTextEdit(self.Tab_Info)
        self.textEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout_8.addWidget(self.textEdit)
        self.verticalLayout_2.addLayout(self.verticalLayout_8)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/info.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MainTab.addTab(self.Tab_Info, icon7, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.textBrowser = QtGui.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(60, 40, 731, 201))
        self.textBrowser.setReadOnly(False)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.textBrowser_2 = QtGui.QTextBrowser(self.tab)
        self.textBrowser_2.setGeometry(QtCore.QRect(420, 310, 381, 201))
        self.textBrowser_2.setReadOnly(False)
        self.textBrowser_2.setObjectName(_fromUtf8("textBrowser_2"))
        self.calendarWidget = QtGui.QCalendarWidget(self.tab)
        self.calendarWidget.setGeometry(QtCore.QRect(40, 300, 341, 201))
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/draft.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MainTab.addTab(self.tab, icon8, _fromUtf8(""))
        self.verticalLayout.addWidget(self.MainTab)
        self.verticalLayout_4.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.MainTab.setCurrentIndex(4)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Data Analysis Package", None))
        self.Btn_Reset.setToolTip(_translate("MainWindow", "Click to restart program", None))
        self.pushButton.setToolTip(_translate("MainWindow", "Click to exit", None))
        self.label_20.setText(_translate("MainWindow", "Splitter mask", None))
        self.label_19.setText(_translate("MainWindow", "Last row number", None))
        self.label_13.setText(_translate("MainWindow", "Thirst column number", None))
        self.label_17.setText(_translate("MainWindow", "Thirst row number", None))
        self.Btn_Import_ChooseFile.setText(_translate("MainWindow", "Choose file", None))
        self.RBtn_PropInR.setText(_translate("MainWindow", "Row", None))
        self.RBtn_PropInC.setText(_translate("MainWindow", "Column", None))
        self.label_15.setText(_translate("MainWindow", "Object properties in:", None))
        self.label_18.setText(_translate("MainWindow", "Object\'s names in file", None))
        self.label_16.setText(_translate("MainWindow", "Last column number", None))
        self.label_21.setText(_translate("MainWindow", "Param\'s names in file", None))
        self.label.setText(_translate("MainWindow", "Last param is a class", None))
        self.Btn_Import.setText(_translate("MainWindow", "Import", None))
        self.Btn_PrepareDate.setText(_translate("MainWindow", "Prepare", None))
        self.label_23.setText(_translate("MainWindow", "Total number of properties", None))
        self.label_22.setText(_translate("MainWindow", "Total number of objects", None))
        self.Lbl_NumObj.setText(_translate("MainWindow", "0", None))
        self.Lbl_NumPrp.setText(_translate("MainWindow", "0", None))
        self.label_2.setText(_translate("MainWindow", "Total number of classes", None))
        self.Lbl_NumCls.setText(_translate("MainWindow", "0", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.Tab_Import), _translate("MainWindow", "Import", None))
        self.label_12.setText(_translate("MainWindow", "Method", None))
        self.RBtn_UsePC.setText(_translate("MainWindow", "Principal components", None))
        self.radioButton_2.setText(_translate("MainWindow", "Factor analysis", None))
        self.RBtn_PC_scale.setText(_translate("MainWindow", "Scale data with sigma", None))
        self.Btn_CalculatePC.setText(_translate("MainWindow", "Calculate Principal Components", None))
        self.label_14.setText(_translate("MainWindow", "New dimension", None))
        self.LEdt_PC_dim.setText(_translate("MainWindow", "2", None))
        self.label_11.setText(_translate("MainWindow", "Variance threshold", None))
        self.Btn_ReducePC.setText(_translate("MainWindow", "Reduce dimension", None))
        self.Lbl_PCdim.setText(_translate("MainWindow", "0", None))
        self.label_5.setText(_translate("MainWindow", "PC dimension", None))
        self.label_3.setText(_translate("MainWindow", "PC var. part", None))
        self.Lbl_PCvar.setText(_translate("MainWindow", "0", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.Tab_Transform), _translate("MainWindow", "Transform", None))
        self.RBtn_MultiGraphPlot_UsePC1.setText(_translate("MainWindow", "Use PC", None))
        self.RBtn_MultiGraphPlot_UsePCred1.setText(_translate("MainWindow", "Use PC red.", None))
        self.Btn_MultiGraphPlot1.setText(_translate("MainWindow", "Plot", None))
        self.RBtn_MultiGraphPlot_UsePC2.setText(_translate("MainWindow", "Use PC", None))
        self.RBtn_MultiGraphPlot_UsePCred2.setText(_translate("MainWindow", "Use PC red.", None))
        self.Btn_MultiGraphPlot2.setText(_translate("MainWindow", "Plot", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.Tab_plot), _translate("MainWindow", "Plot", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.Tab_Console), _translate("MainWindow", "Console", None))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; color:#000080;\">Data analysis package</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Д</span>анный программный продукт позволяет проводить анализ данных, заданных в матричной форме Объекты/Признаки. В качестве объектов могут, например, выступать результаты экспериментальных выборок.</p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-style:italic;\">1. Импорт данных.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Д</span>ля импорта данных из excel файлов откройте вкладку Import и задайте основные параметры представления данных в файле:</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Если требуется импортировать строки данных,  начиная не с первой строки (заголовки, которые могут находиться в первой строке за отдельную строку не считаются), то включите флаг &quot;Thirst row number&quot; и укажите номер первой строки для считывания. Аналогично, если при чтении файла следует остановиться на определенной строке, включите флаг &quot;Last row number&quot;.</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Для столбцов (&quot;Thirst column number&quot; и &quot;Last column number&quot;) все полностью аналогично предыдущему пункту (заголовки, которые могут находиться в первом столбце за отдельный стобец не считаются).</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Если в файле используется особый разделить для данных в строке (по умолчанию: точка с запятой между данными и символ перевода строки без точки с запятой в конце строки), то укажите его в одинарных кавычках в поле &quot;Splitter mask&quot;. Данный пункт актуален только для csv и txt файлов<span style=\" font-style:italic; text-decoration: underline;\"> (в текущей версии не поддерживается)</span>.</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Выберите направление расположения данных (&quot;Object properties in&quot;): каждая строка соответствует набору значений признаков эксперимента (выбрано по умолчанию) или каждый столбец соответствует набору значений признаков эксперимента.</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Если в файле в первой строке и/или столбце записаны имена свойств и/или имена для каждого из проведенных экспериментов, установите соответствующие флаги (&quot;Object\'s names in file&quot; и &quot;Param\'s names in file&quot;).</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Если последний из приведенных в таблице данных признаков соответствует номеру класса объекта, то включите опцию &quot;Last param in a class&quot;.</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- По завершении выбора параметров данных в файле, нажмите кнопку &quot;Import&quot; для импорта данных из файла, а затем, при отсутствии сообщений об ошибках, кнопку &quot;Prepare&quot; для первичной обработки данных. При успешной обработке в текущей вкладке будут отображены параметры входных данных в текстовой и графической форме (количества объектов, параметров и классов, распределения для значений параметров и сравнение распределений для классов).</p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-style:italic;\">2. Преобразование данных.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-style:italic;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Д</span>ля преобразования импортированных и подготовленных данных к пространству меньшей размерности перейдите во вкладку &quot;Transform&quot;.</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Если при построении главных компонент помимо центрирования данных требуется их нормировка на среднее квадратичное отклонение, включите флаг &quot;Scale data with sigma&quot;.</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Нажмите кнопку &quot;Calculate Principal Components&quot;. При успешной обработке в текущей вкладке будет отогражен график вклада главных компонент в дисперсию исходных данных.</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Включите переключатель &quot;New dimension&quot; и, используя распределение, приведенное на графике, выберете требуемую размерность подпространства.</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Нажмите кнопку &quot;Reduce dimension&quot; для построения подпространства.</p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-style:italic;\">3. Анализ данных.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-style:italic;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Д</span>ля анализа взаимозависимости параметров входных данных и визуальной классификации, перейдите во вкладку &quot;Plot&quot;. Для удобства визуального сравнения данных область данной вкладки разбита на две горизонтальные подобласти, в каждой из которых возможно построение графика.</p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Выберете тип отображения графика. По умолчанию графики будут построены в исходном полном пространстве. При выборе флага &quot;Use PC&quot; построение будет произведено в пространстве главных компонент, а при выборе флага &quot;Use PC red&quot; - в подпространстве главных компонент.</p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-style:italic;\">4. Контроль за ходом выполнения.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-style:italic;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Д</span>ля анализа процесса работы программы перейдите во вкладку &quot;Console&quot;. В данной вкладке производится вывод сообщений, характеризующих процесс выполнения программы. Сообщения разделены на 4 типа (каждый из типов имеет собственный цвет шрифта): ошибки, предупреждения, сообщения о результатах и сообщения о процессе.</p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-style:italic;\">5. Модификация и экспорт графиков.</span></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt; font-style:italic;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Д</span>ля изменения внешнего вида графиков,а также сохранения их на диск, нажмите на кнопку с характерной пиктограммой подле интересуемого графика. После нажатия кнопка останется в зажатом состоянии,а в левой верхней части рабочего окна появится меню для модификации свойств графика. При повторном нажатии кнопки она вернется в ненажатое состояние, а меню исчезнет.</p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Примечание: прежде чем открывать меню редактирования для очереднего графика, следует закрыть уже открытое меню при его наличии.</p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.Tab_Info), _translate("MainWindow", "Info", None))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">You can write your notes here</span></p></body></html>", None))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">and here...</span></p></body></html>", None))
        self.MainTab.setTabText(self.MainTab.indexOf(self.tab), _translate("MainWindow", "Draft", None))

import resources_rc
